version: '3.8'

services:
  belka-game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: belka-game
    restart: unless-stopped
    ports:
      - "80:80"  # Map container's port 80 to host's port 80
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3