version: '3.8'

services:
  db:
    image: postgres:15
    container_name: belka-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  belka-game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: belka-game
    restart: unless-stopped
    ports:
      - "3000:3000"  # Bot API port
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./data:/app/data  # For persistent bot data
      - ./logs:/app/logs  # For logs

volumes:
  db_data: